(()=>{const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const stage=$('.hero-stage-label b');if(stage)stage.textContent='MENTORA / 17';
// Restore the founder portrait in the live preview.
$$('.founder-photo-card picture,.portrait-photo-wrap picture,.founder-team-photo picture').forEach(p=>{p.innerHTML='<img src="assets/founder.webp" width="768" height="1024" loading="lazy" decoding="async" alt="Abdusamad Shatursunov">';});$$('.portrait-photo').forEach(img=>img.src='assets/founder.webp');
// Three-phase hero narrative.
const hero=$('.hero');if(hero&&!$('#heroPhaseRail')){const rail=document.createElement('div');rail.className='hero-phase-rail';rail.id='heroPhaseRail';rail.setAttribute('aria-hidden','true');rail.innerHTML='<small>LIVE PRODUCT LOGIC</small><div class="hero-phase-list"><div class="hero-phase is-active" data-v17-phase="0"><i>01</i><div><b>PROBLEM</b><span>Рутина учителя</span></div></div><div class="hero-phase" data-v17-phase="1"><i>02</i><div><b>AI CORE</b><span>AI-логика урока</span></div></div><div class="hero-phase" data-v17-phase="2"><i>03</i><div><b>SYSTEM</b><span>4 роли · 1 экосистема</span></div></div></div><div class="hero-phase-meter"><span></span></div>';const anchor=$('.hero-system',hero)||$('.hero-wordmark',hero);anchor?anchor.after(rail):hero.append(rail);const phases=$$('[data-v17-phase]',rail),meter=$('.hero-phase-meter span',rail),readout=$('.hero-core-readout b',hero);let last=-1;const sync=()=>{const r=hero.getBoundingClientRect(),p=Math.max(0,Math.min(.999,-r.top/Math.max(1,r.height*.82))),i=Math.min(2,Math.floor(p*3));meter.style.width=Math.max(7,p*100)+'%';if(i===last)return;last=i;hero.dataset.v17Phase=String(i);phases.forEach((x,j)=>x.classList.toggle('is-active',i===j));if(readout)readout.textContent=['01 / PROBLEM','02 / AI CORE','03 / ECOSYSTEM'][i];const cube=$('#mentoraCube');if(cube&&!reduce)cube.animate([{filter:'brightness(1.35)',transform:'scale(1.035)'},{filter:'brightness(1)',transform:'scale(1)'}],{duration:420,easing:'cubic-bezier(.16,1,.3,1)'});};addEventListener('scroll',sync,{passive:true});sync();}
// Founder product thesis.
const founder=$('#founder');if(founder&&!$('.founder-thesis-v17',founder)){const box=document.createElement('div');box.className='founder-thesis-v17 reveal';box.innerHTML='<div class="ft-copy"><small>03A / PRODUCT THESIS</small><h3>Как принимаются продуктовые решения.</h3><p>Каждый новый слой Mentora проходит один и тот же фильтр: он должен решать реальную образовательную задачу, быть понятным пользователю и усиливать систему целиком.</p></div><div class="ft-stage"><div class="ft-tabs"><button class="is-active" type="button" data-ft="0"><span>01</span><b>Education first</b></button><button type="button" data-ft="1"><span>02</span><b>AI with purpose</b></button><button type="button" data-ft="2"><span>03</span><b>One system</b></button></div><div class="ft-detail" aria-live="polite"><small>01 / EDUCATION FIRST</small><h4>Начинать с задачи, а не с функции.</h4><p>Сначала — проблема учителя, ученика или школы. Только потом — интерфейс, автоматизация и AI.</p></div></div>';const note=$('.founder-note',founder);note?note.after(box):founder.append(box);const data=[['01 / EDUCATION FIRST','Начинать с задачи, а не с функции.','Сначала — проблема учителя, ученика или школы. Только потом — интерфейс, автоматизация и AI.'],['02 / AI WITH PURPOSE','Автоматизировать рутину, а не мышление.','AI берёт на себя повторяющиеся операции и подготовку материалов, сохраняя ключевые решения за человеком.'],['03 / ONE SYSTEM','Соединять процессы, а не множить сервисы.','Mentora стремится связывать урок, класс, задания, результаты и роли в одном понятном рабочем потоке.']],buttons=$$('[data-ft]',box),detail=$('.ft-detail',box),k=$('small',detail),h=$('h4',detail),p=$('p',detail);const set=i=>{buttons.forEach((b,j)=>b.classList.toggle('is-active',i===j));k.textContent=data[i][0];h.textContent=data[i][1];p.textContent=data[i][2];if(!reduce){detail.classList.remove('is-switching');void detail.offsetWidth;detail.classList.add('is-switching');}};buttons.forEach((b,i)=>{b.addEventListener('click',()=>set(i));b.addEventListener('pointerenter',()=>{if(innerWidth>900)set(i)});});}
// Chapter cue for long-form scrolling.
if(innerWidth>760){const cue=document.createElement('div');cue.className='chapter-cue-v17';cue.setAttribute('aria-hidden','true');cue.innerHTML='<span>01</span><div><small>ГЛАВА</small><b>История</b></div>';document.body.append(cue);const number=$('span',cue),name=$('b',cue),links=$$('[data-chapter-link]'),map=new Map(links.map(a=>[a.dataset.chapterLink,{n:$('span',a)?.textContent?.trim()||'',name:$('b',a)?.textContent?.trim()||a.dataset.chapterLink}]));let timer,first=true;const show=id=>{const d=map.get(id);if(!d)return;number.textContent=d.n;name.textContent=d.name;cue.classList.remove('show');void cue.offsetWidth;cue.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>cue.classList.remove('show'),1050);};const sections=[...map.keys()].map(id=>document.getElementById(id)).filter(Boolean);const io=new IntersectionObserver(es=>{const e=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!e)return;if(first){first=false;return;}show(e.target.id);},{rootMargin:'-28% 0px -58% 0px',threshold:[0,.16,.35]});sections.forEach(s=>io.observe(s));}
const badge=document.createElement('div');badge.className='v17-badge';badge.innerHTML='MENTORA / <b>V17 LIVE</b>';document.body.append(badge);
})();